run:
  timeout: 10m

issues:
  exclude-dirs:
    - vendor

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/ziyan/gatewaysshd)

  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gocritic
    - misspell
  disable:
    - typecheck
