run:
  timeout: 10m
  go: "1.23"

issues:
  exclude-dirs:
    - vendor
  exclude-use-default: false
  exclude-generated-strict: false

linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
