run:
  timeout: 10m
  go: "1.23"

issues:
  exclude-use-default: false

linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gocritic
    - misspell
