name: gatewaysshd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.24.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Check
      run: make check
      
    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        args: --timeout=10m
    
    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
